modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"
issueTrackerURL="https://github.com/BananaBank/HauntedFields/issues/"

[[mods]]
modId="hauntedfields"
version="${file.jarVersion}"
displayName="Haunted Fields"
credits="The exaggerated swagger of the Rusty Team. Sounds by https://quicksounds.com"
authors="TheDarkColour, cfrishausen, bobertrd"

description='''
Spooky scarecrows O_o
'''

[[dependencies.hauntedfields]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.hauntedfields]]
    modId="geckolib3"
    mandatory=true
    versionRange="[3.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.hauntedfields]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
